### ISSUE TITLE
[Security] Workflow update-copyright-years-in-license-file.yml is using vulnerable action FantasticFiasco/action-update-license-year

### ISSUE THREAD

**Issue by Freakston** [FantasticFiasco/todo-cqrs#287]
The workflow update-copyright-years-in-license-file.yml is referencing action FantasticFiasco/action-update-license-year using references v2. However this reference is missing the commit [0dd479f24c62cdbbbce52c7f2ee4277c778cae06](https://github.com/FantasticFiasco/action-update-license-year/commits/0dd479f24c62cdbbbce52c7f2ee4277c778cae06) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by FantasticFiasco** [comment]
A new release of [FantasticFiasco/action-update-license-year](https://github.com/FantasticFiasco/action-update-license-year) has been made available, and the git tag `v2` has been updated to reflect that as well.

Thanks for reporting the issue!
